### ISSUE TITLE
No Update available

### ISSUE THREAD

**Issue by babsitz** [YahnisElsts/wp-update-server#45] opened 2017-01-09 19:15 UTC
Hello,

I have a problem with the update server. The JSON data are retrieved regularly according to the log file. Look here:

[2017-01-09 18:30:10 +0000] 178.254.38.202 GET get_metadata drkwp_v2 2.0.0 4.7 http://drkwp2016.klebsattel.de action = get_metadata & slug = drkwp_v2 & installed_version = 2.0.0

When I call the following address: https://www.klebsattel.de/wp-update-server/?action=get_metadata&slug=drkwp_v2 appears there, that version 2.0.1 is available. When I log in to Wordpress the update is not displayed. What could be the reason?

Best wishes
Jörg Klebsattel

**Comment by YahnisElsts** [comment] 2017-01-09 19:21
There are too many possibilities to list. Instead, install [Debug Bar](https://srd.wordpress.org/plugins/debug-bar/) and look at the "PUC (your-plugin-slug)" panel. Does everything look correct there? Click "Request Info". Does it display your data or is there an error message of some kind?

**Comment by babsitz** [comment] 2017-01-09 20:09
You mean for themes >> Design, Theme and then Themes?

 

Then there is shown:

Cache Hits: 545
Cache Misses: 73

*	Group: options - ( 40.01k )
*	Group: default - ( 0.03k )
*	Group: users - ( 0.43k )
*	Group: userlogins - ( 0.03k )
*	Group: useremail - ( 0.04k )
*	Group: userslugs - ( 0.03k )
*	Group: user_meta - ( 1.62k )
*	Group: themes - ( 0.54k )
*	Group: counts - ( 0.17k )

 

 

 

Von: Yahnis Elsts [mailto:notifications@github.com] 
Gesendet: Montag, 9. Januar 2017 20:21
An: YahnisElsts/wp-update-server <wp-update-server@noreply.github.com>
Cc: babsitz <joerg@klebsattel.de>; Author <author@noreply.github.com>
Betreff: Re: [YahnisElsts/wp-update-server] No Update available (#45)

 

There are too many possibilities to list. Instead, install Debug Bar <https://srd.wordpress.org/plugins/debug-bar/>  and look at the "PUC (your-plugin-slug)" panel. Does everything look correct there? Click "Request Info". Does it display your data or is there an error message of some kind?

**Comment by YahnisElsts** [comment] 2017-01-09 20:44
Ah, I incorrectly assumed you were talking about a plugin, not a theme.

Looking at the source code, I think I see what the problem is: for theme updates to work, the `style.css` file must include either a `Theme URI` header or a `Details URI` header. Your theme has a `Theme URL` header, but that's non-standard and is not supported by this update checker ([here's a list of standard headers](https://codex.wordpress.org/File_Header)). 

Rename `Theme URL` to `Theme URI`, upload the new update ZIP, and verify that the JSON data now includes a `details_url` key. Then updates should work.

**Comment by babsitz** [comment] 2017-01-09 20:50
Thank you! Now it works fine. That was the issue

**Comment by YahnisElsts** [comment] 2017-01-09 20:55
All right, that's good to hear. Closing this now.

**Closed by YahnisElsts** 2017-01-09 20:55 UTC
