### ISSUE TITLE
/icons conflicts with Apache

### ISSUE THREAD

**Issue by mbaierl** [YahnisElsts/wp-update-server#70] opened 2019-03-24 09:56 UTC
By default apache serves its own icons under /icons, so the uploaded WP Plugin Icons will never be loaded - simply a 404 not found.

My suggestion is to rename the /icons folder to something else, i.e. wp-icons?

**Comment by k9t9** [comment] 2019-03-25 02:49
Although this will be a problem only in edge-cases - I can confirm it can be in fact an issue.

It can be resolved by the method suggested by @mbaierl or other methods for example : 
- move` /icons ` ( and `/banners` ) to other folder - for example `assets` .
- get the icon ( and banner ) from another ( might be external ) defined URL.
- use a string for base64 image without actual icons.

I must say that I do not know the code  well and I did not review it or the methods implemented- so  I am not advocating for any of those - all might be good or very bad suggestion.  But they are still options.

**Comment by mbaierl** [comment] 2019-03-25 08:28
I've simply renamed the folder and updated the following file:

```
		$this->assetDirectories = array(
			'banners' => $this->bannerDirectory,
			'icons'   => $serverDirectory . '/wp-icons', // updated
		);
```

Works like a charm.

**Comment by YahnisElsts** [comment] 2019-03-25 12:36
Thank you for the report. Personally, renaming the `icons` directory seems like easiest solution so far.

@k9t9 Why move the `banners` directory? Just for consistency, or is there a similar aliasing issue with `banners` as well?

**Comment by k9t9** [comment] 2019-03-25 13:48
@YahnisElsts 

> Why move the banners directory? Just for consistency, or is there a similar aliasing issue with banners as well?

No aliasing issue AFAIK on any system . Just for consistency of having all the `assets` ( read : images )  in one place .. well .. ` assets` .

**Closed** 2019-03-26 10:04 UTC

**Comment by YahnisElsts** [comment] 2019-03-26 10:06
All right, I've moved both directories to `package-assets`.

(I used `package-assets` instead of `assets` because the update server itself might need some CSS/JS one day and there should be a way to distinguish between server assets and plugin/theme assets.)
