### ISSUE TITLE
فایل های ترجمه کار نمیکند

### ISSUE THREAD

**Issue by afagh11943** [YahnisElsts/wp-update-server#87] opened 2020-11-17 15:36 UTC
متاسفانه فایل های ترجمه فراخوانی نمی شود و کلمات فقط به زبان انگلیسی نمایش داده می شود

**Comment by YahnisElsts** [comment] 2020-11-17 15:58
_Translation by Google Translate:_
> Unfortunately the translation files are not called and the words are displayed in English only

I can't seem to reproduce that issue. As a test, I changed the language on one of my sites to Italian (PUC has translation files for this language) and the "Check for updates" link was correctly translated:

![put-translation-example](https://user-images.githubusercontent.com/2527434/99412605-99f8fa00-28fd-11eb-8ec4-c7b917467e9b.png)

Then I switched to German and that also worked as expected:

![puc-translation-example-2](https://user-images.githubusercontent.com/2527434/99413308-50f57580-28fe-11eb-95ce-6e34c9bfcc78.png)

Which language are you trying to use, and does PUC actually have a translation file for that language?

**Comment by afagh11943** [comment] 2020-11-17 16:08
منظور من موارد زیر است:
The test aminb plugin is up to date.

A new version of the elementor plugin is available.

**Comment by afagh11943** [comment] 2020-11-17 16:10
<a href="https://uupload.ir/" target="_blank"><img src="https://uupload.ir/files/74g_untitled.jpg" border="0" alt="آپلود عکس" /></a>

**Comment by afagh11943** [comment] 2020-11-17 16:11
``<a href="https://uupload.ir/" target="_blank"><img src="https://uupload.ir/files/rgaq_untitled1.png" border="0" alt="آپلود عکس" /></a>

**Comment by YahnisElsts** [comment] 2020-11-17 16:19
Is this the Persian language (`fa_IR`)? It looks like the translation that we have for that language is more than 4 years old and it is missing translations for a few messages including the ones shown in your screenshots. 

I don't know any Persian so I can't fix this myself. If you're familiar with how plugin translation works, feel free to submit updated `.po` and `.mo` files for this language.

**Comment by afagh11943** [comment] 2020-11-17 16:41
فایل زبان جدید را ساختم اما مشکل رفع نگردید
دانلود فایل زبانم فارسی جدید
https://uupload.ir/view/3e_plugin-update-checker-fa_ir.zip/

**Comment by YahnisElsts** [comment] 2020-11-17 16:49
It looks like you only have a `.po` file. For the translation to work, you also need to compile that `.po` file to a `.mo` file and put that in the same directory. Here, try this `.mo` file:
[plugin-update-checker-fa_IR.zip](https://github.com/YahnisElsts/wp-update-server/files/5554901/plugin-update-checker-fa_IR.zip)

**Comment by afagh11943** [comment] 2020-11-17 17:09
خیر در فایل اصلی پلاگین هر دو فایل را قرار دادم
این فایل را برای بررسی شما قرار دادم

**Comment by afagh11943** [comment] 2020-11-17 17:14
اگر ممکن است شما با استفاده ار فایلی که من فرستادم
شما فایل دوم را تولید کنید
و زبان سایت را روی فارسی قرار دهید 
و موضوع را بررسی کنید

**Comment by YahnisElsts** [comment] 2020-11-17 17:22
All right, here it is:
![puc-fa-check-for-updates](https://user-images.githubusercontent.com/2527434/99423987-d3376700-2909-11eb-9b7c-5fef90f7d67a.png)

It looks like the "a new version is available" message is translated. I'm using the `.po` file that you sent me and a `.mo` file that I generated myself.

If it's still not working for you, could it be that there are multiple active plugins on your site that are using different versions of `plugin-update-checker`? In general, only one copy of PUC will be able to load its translations, so if an older version is being loaded first, your new translation might not show up.

**Comment by afagh11943** [comment] 2020-11-17 17:36
نسخه 4.10 را دانلود کردم
در مرحله بعد کامل پوشه نسخه 4.10را به داخل پوشه پلاگین اضافه کردم

**Comment by YahnisElsts** [comment] 2020-11-17 17:47
Right, but are the any *other* active plugins or themes that could be using this update checker?

**Comment by afagh11943** [comment] 2020-11-17 17:52
بله
یک پلاگین دیگر از این سیستم استفاده میکند
ولی در هر دو پلاگین از نسخه 4.10 استفاده شده است

**Comment by YahnisElsts** [comment] 2020-11-17 17:59
So could it be that the other plugin is executed first, so it loads its old copy of the `.mo` file and not your new version? Try placing your `.po`/`.mo` files in the `languages` subdirectories of both plugins.

**Comment by afagh11943** [comment] 2020-11-17 18:10
اگر امکان دارد فایل هایی را که شما تولید کردید را اپلود نمایید تا من دانلود کنم و مجدد امتحان کنم

**Comment by YahnisElsts** [comment] 2020-11-17 18:37
I already included the `.mo` file in an earlier comment. But sure, here are both files:
[plugin-update-checker-fa_IR.zip](https://github.com/YahnisElsts/wp-update-server/files/5555479/plugin-update-checker-fa_IR.zip)

**Comment by afagh11943** [comment] 2020-11-18 05:06
مشکل برطرف گردید
موضوع مشکل نکته ای بود که شمکا به آن اشاره کرده بودید
متشکرم

**Comment by YahnisElsts** [comment] 2020-11-18 10:08
All right, I'll close this then.

**Closed by YahnisElsts** 2020-11-18 10:08 UTC
