### ISSUE TITLE
readme.txt and UTF-8 characters error

### ISSUE THREAD

**Issue by artprojectgroup** [YahnisElsts/wp-update-server#32] opened 2015-11-02 11:39 UTC
I detect problems with readme.txt and JSON encode. If you use spanish symbols like ñ or ó, when the plugin update checker decode it show Ã± or Ã³, not ñ or ó.

Can you check it?

Kind regards.

**Comment by 834rd** [comment] 2015-11-02 12:54
Sorry, i only speak and write german in my plugins and our keybord have no keys like this :-)

Greetings

**Comment by artprojectgroup** [comment] 2015-11-02 15:06
Can you try a word like España, Camión or Ánade, please?

Thank you.

**Comment by YahnisElsts** [comment] 2015-11-02 15:08
I can confirm that this is a bug. It looks like there was some left-over code in the parser that assumed readme.txt would be encoded as ISO-8859-1. 

Please try the latest master branch. It should be fixed there.

**Comment by artprojectgroup** [comment] 2015-11-02 15:12
I tried that fix before, but it doesn't work :-(

Try make a test with a readme.txt like this: https://wordpress.org/plugins/google-video-sitemap-feed-with-multisite-support/

Thank you.

**Comment by artprojectgroup** [comment] 2015-11-02 15:13
http://plugins.svn.wordpress.org/google-video-sitemap-feed-with-multisite-support/trunk/readme.txt

**Comment by artprojectgroup** [comment] 2015-11-02 15:15
https://www.dropbox.com/s/ms8a0l32seu4xsm/readme.txt?dl=0

**Comment by YahnisElsts** [comment] 2015-11-02 15:18
All right, I tried it with that plugin. The result looks fine to me. Here's a screenshot of the JSON output:
![screenshot 2015-11-02 17 16 34](https://cloud.githubusercontent.com/assets/2527434/10885379/a5473dec-8185-11e5-92a3-42e0bb1d17e8.png)

How exactly did you test the fix? Did you remember to clear the metadata cache first?

**Comment by artprojectgroup** [comment] 2015-11-02 17:05
Fixed ;-)

I tried that fix but with other modifications, never alone :-(

Good job.

Kind regards.

P.D: now fix the screenshot tab ;-)

**Comment by YahnisElsts** [comment] 2015-11-02 17:49
All right, that's good to hear. I'll close this now.

> P.D: now fix the screenshot tab ;-)

Technically speaking, that's not a bug. The screenshots tab is just one of those wordpress.org features that's currently not supported by this particular update server. It doesn't track the number of active installs or plugin versions, either :-) But your interest is noted!

**Closed by YahnisElsts** 2015-11-02 17:49 UTC
Labels: bug
